import streamlit as st
from PIL import Image


def main():
    st.set_page_config(page_title="GPTPPT - Notes to Slides Generator", layout="wide")

    st.title("Welcome to GPTPPT 🚀")
    st.subheader("Transform your notes into beautiful presentations with AI")

    col1, col2 = st.columns([2, 1])

    with col1:
        st.write(
            """
        GPTPPT is an innovative tool that uses AI to convert your notes or ideas into 
        professional-looking presentation slides. Whether you're a student, teacher, 
        or business professional, GPTPPT helps you create engaging presentations in minutes!
        
        ### Key Features:
        - 🧠 AI-powered content generation
        - 🎨 Customizable themes and layouts
        - 📊 Support for various output formats (PDF, PPTX)
        - 🚀 Fast and easy to use
        """
        )

        if st.button(
            "Get Started",
            type="primary",
            use_container_width=True,
        ):
            st.switch_page("pages/Generate.py")

    with col2:
        # Replace with an actual image of your app or a sample slide
        st.image("static/1.png", caption="GPTPPT in action")

    st.header("How It Works")
    col1, col2, col3 = st.columns(3)
    with col1:
        st.write("1. Enter your notes or ideas")
        st.image("static/1.png", caption="Step 1")
    with col2:
        st.write("2. Customize your presentation")
        st.image("static/1.png", caption="Step 2")
    with col3:
        st.write("3. Generate and download")
        st.image("static/1.png", caption="Step 3")

    st.header("Sample Presentations")
    st.write("Check out these example presentations created with GPTPPT:")
    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="Download Sample PDF",
            data=b"Sample PDF content",  # Replace with actual PDF data
            file_name="sample_presentation.pdf",
            mime="application/pdf",
        )
    with col2:
        st.download_button(
            label="Download Sample PPTX",
            data=b"Sample PPTX content",  # Replace with actual PPTX data
            file_name="sample_presentation.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )

    st.header("Frequently Asked Questions")
    faq_data = [
        (
            "Is my data safe?",
            "Yes, we prioritize your privacy. Your notes are processed securely and are not stored after generating the presentation.",
        ),
        (
            "How is this service free?",
            "GPTPPT is currently offered as a free service to gather user feedback. We may introduce premium features in the future.",
        ),
        (
            "Can I use the generated presentations commercially?",
            "Yes, you have full rights to use the presentations generated by GPTPPT for any purpose, including commercial use.",
        ),
        (
            "What if I'm not satisfied with the generated slides?",
            "You can always edit the generated markdown or regenerate the slides with different input. We're constantly improving our AI to provide better results.",
        ),
    ]

    for question, answer in faq_data:
        with st.expander(question):
            st.write(answer)

    st.markdown("---")
    st.markdown(
        """
        <div style="text-align: center;">
            <p>If you find GPTPPT helpful, consider supporting the project:</p>
            <a href="https://www.buymeacoffee.com/aldrinjenson" target="_blank">
                <img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;">
            </a>
        </div>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
